CREATE TABLE drinking_water_availability(
   region                    INTEGER  NOT NULL
  ,region_name               VARCHAR(29) NOT NULL
  ,year                      INTEGER  NOT NULL
  ,safe_drinking_water_rural NUMERIC(4,1)
  ,safe_drinking_water_total NUMERIC(4,1)
  ,safe_drinking_water_urban NUMERIC(4,1)
  ,PRIMARY KEY(region,year)
);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (1,'Total, all countries or areas',2005,48,66.1,84.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (1,'Total, all countries or areas',2010,55.5,70.8,85.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (1,'Total, all countries or areas',2015,54.8,71.2,85.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (5,'South America',2005,36.2,72.1,80.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (5,'South America',2010,38.5,73.3,80.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (5,'South America',2015,40.8,74.4,81.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (8,'Albania',2005,NULL,52.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (8,'Albania',2010,NULL,61.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (8,'Albania',2015,NULL,68.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (9,'Oceania',2005,NULL,NULL,93.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (9,'Oceania',2010,NULL,NULL,95.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (9,'Oceania',2015,NULL,NULL,95.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (11,'Western Africa',2005,NULL,21,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (11,'Western Africa',2010,NULL,23.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (11,'Western Africa',2015,NULL,25.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (12,'Algeria',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (12,'Algeria',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (12,'Algeria',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (13,'Central America',2005,NULL,44.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (13,'Central America',2010,NULL,46.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (13,'Central America',2015,NULL,50.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (14,'Eastern Africa',2005,4.1,12.3,41.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (14,'Eastern Africa',2010,5.7,14.9,44.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (14,'Eastern Africa',2015,7.5,17.8,47.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (15,'Northern Africa',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (15,'Northern Africa',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (15,'Northern Africa',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (18,'Southern Africa',2005,NULL,NULL,89.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (18,'Southern Africa',2010,NULL,NULL,88.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (18,'Southern Africa',2015,NULL,NULL,85);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (20,'Andorra',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (20,'Andorra',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (20,'Andorra',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (21,'Northern America',2005,NULL,99,99.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (21,'Northern America',2010,NULL,99,99.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (21,'Northern America',2015,NULL,99,99.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (29,'Caribbean',2001,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (30,'Eastern Asia',2005,NULL,NULL,94.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (30,'Eastern Asia',2010,NULL,NULL,93.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (30,'Eastern Asia',2015,NULL,NULL,92.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (31,'Azerbaijan',2005,NULL,56.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (31,'Azerbaijan',2010,NULL,67.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (31,'Azerbaijan',2015,NULL,71.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (32,'Argentina',2005,NULL,98,98.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (32,'Argentina',2010,NULL,98.3,98.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (32,'Argentina',2015,NULL,98.5,98.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (34,'Southern Asia',2005,43.1,49.1,62.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (34,'Southern Asia',2010,48.8,52.7,60.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (34,'Southern Asia',2015,54.9,56.2,58.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (36,'Australia',2005,NULL,NULL,98.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (36,'Australia',2010,NULL,NULL,98.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (36,'Australia',2015,NULL,NULL,98.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (39,'Southern Europe',2005,NULL,88.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (39,'Southern Europe',2010,NULL,91.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (39,'Southern Europe',2015,NULL,93.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (40,'Austria',2005,NULL,98.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (40,'Austria',2010,NULL,98.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (40,'Austria',2015,NULL,98.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (48,'Bahrain',2005,NULL,98.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (48,'Bahrain',2010,NULL,98.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (48,'Bahrain',2015,NULL,98.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (50,'Bangladesh',2005,60,55.9,44.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (50,'Bangladesh',2010,60.7,55.8,44.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (50,'Bangladesh',2015,61.4,55.7,44.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (51,'Armenia',2005,NULL,43.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (51,'Armenia',2010,NULL,57.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (51,'Armenia',2015,NULL,60.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (53,'Australia and New Zealand',2005,NULL,NULL,93.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (53,'Australia and New Zealand',2010,NULL,NULL,95.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (53,'Australia and New Zealand',2015,NULL,NULL,96.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (56,'Belgium',2005,NULL,99.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (56,'Belgium',2010,NULL,98.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (56,'Belgium',2015,NULL,98.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (64,'Bhutan',2005,23.6,30.1,44.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (64,'Bhutan',2010,25.9,32.4,44.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (64,'Bhutan',2015,27.6,34.2,44.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (68,'Bolivia (Plurin. State of)',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (68,'Bolivia (Plurin. State of)',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (68,'Bolivia (Plurin. State of)',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (70,'Bosnia and Herzegovina',2005,NULL,87.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (70,'Bosnia and Herzegovina',2010,NULL,88.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (70,'Bosnia and Herzegovina',2015,NULL,88.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (72,'Botswana',2005,NULL,NULL,84.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (72,'Botswana',2010,NULL,NULL,84.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (72,'Botswana',2015,NULL,NULL,84.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (76,'Brazil',2005,NULL,NULL,95.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (76,'Brazil',2010,NULL,NULL,97.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (76,'Brazil',2015,NULL,NULL,97.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (100,'Bulgaria',2005,NULL,97.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (100,'Bulgaria',2010,NULL,96.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (100,'Bulgaria',2015,NULL,96.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (112,'Belarus',2005,NULL,82,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (112,'Belarus',2010,NULL,89.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (112,'Belarus',2015,NULL,94.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (116,'Cambodia',2005,12.5,19.2,47.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (116,'Cambodia',2010,14.2,21.6,51.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (116,'Cambodia',2015,15.9,24.1,55.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (124,'Canada',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (124,'Canada',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (124,'Canada',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (142,'Asia',2005,51.2,65.4,85.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (142,'Asia',2010,61.7,72.4,85.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (142,'Asia',2015,61.1,72.8,85.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (143,'Central Asia',2005,34.5,55.5,85.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (143,'Central Asia',2010,40.4,59.5,87.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (143,'Central Asia',2012,43,61.2,88);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (143,'Central Asia',2015,NULL,NULL,88.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (144,'Sri Lanka',2005,NULL,NULL,84.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (144,'Sri Lanka',2010,NULL,NULL,88.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (144,'Sri Lanka',2015,NULL,NULL,92.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (145,'Western Asia',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (145,'Western Asia',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (145,'Western Asia',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (150,'Europe',2005,NULL,89.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (150,'Europe',2010,NULL,91.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (150,'Europe',2015,NULL,91.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (151,'Eastern Europe',2005,NULL,81.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (151,'Eastern Europe',2010,NULL,83.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (151,'Eastern Europe',2015,NULL,85.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (152,'Chile',2005,NULL,94.6,98.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (152,'Chile',2010,NULL,97.2,98.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (152,'Chile',2015,NULL,98.2,98.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (154,'Northern Europe',2005,NULL,95.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (154,'Northern Europe',2010,NULL,95.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (154,'Northern Europe',2015,NULL,95.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (155,'Western Europe',2005,NULL,97.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (155,'Western Europe',2010,NULL,97.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (155,'Western Europe',2015,NULL,97.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (156,'China',2005,NULL,NULL,93.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (156,'China',2010,NULL,NULL,92.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (156,'China',2015,NULL,NULL,91.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (170,'Colombia',2005,34.9,69.2,81.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (170,'Colombia',2010,37.3,70.4,81.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (170,'Colombia',2015,39.8,71.1,80.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (175,'Mayotte',2010,NULL,84.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (175,'Mayotte',2015,NULL,84.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (178,'Congo',2005,NULL,31.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (178,'Congo',2010,NULL,34.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (178,'Congo',2015,NULL,37,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (188,'Costa Rica',2005,NULL,78.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (188,'Costa Rica',2010,NULL,86.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (188,'Costa Rica',2015,NULL,89.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (191,'Croatia',2005,NULL,91.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (191,'Croatia',2010,NULL,92.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (191,'Croatia',2015,NULL,90.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (192,'Cuba',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (192,'Cuba',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (192,'Cuba',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (196,'Cyprus',2005,NULL,96.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (196,'Cyprus',2010,NULL,98,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (196,'Cyprus',2015,NULL,99.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (202,'Sub-Saharan Africa',2005,NULL,19.6,44.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (202,'Sub-Saharan Africa',2010,NULL,21.6,45.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (202,'Sub-Saharan Africa',2015,NULL,23.7,46.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (203,'Czechia',2005,NULL,96.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (203,'Czechia',2010,NULL,97.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (203,'Czechia',2015,NULL,97.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (208,'Denmark',2005,NULL,94.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (208,'Denmark',2010,NULL,96,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (208,'Denmark',2015,NULL,96.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (218,'Ecuador',2005,52.3,69.1,79.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (218,'Ecuador',2010,54.2,71.7,82.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (218,'Ecuador',2015,56.2,74.4,84.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (222,'El Salvador',2005,NULL,NULL,81.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (222,'El Salvador',2010,NULL,NULL,76.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (222,'El Salvador',2015,NULL,NULL,77.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (231,'Ethiopia',2005,0.5,6.1,36);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (231,'Ethiopia',2010,1.8,7.9,36.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (231,'Ethiopia',2015,3.9,10.5,37.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (233,'Estonia',2005,NULL,94.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (233,'Estonia',2010,NULL,89.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (233,'Estonia',2015,NULL,81.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (246,'Finland',2005,NULL,95.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (246,'Finland',2010,NULL,98.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (246,'Finland',2015,NULL,96.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (250,'France',2005,NULL,93.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (250,'France',2010,NULL,93.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (250,'France',2015,NULL,93.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (254,'French Guiana',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (254,'French Guiana',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (254,'French Guiana',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (268,'Georgia',2005,NULL,76,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (268,'Georgia',2010,NULL,73.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (268,'Georgia',2015,NULL,73,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (270,'Gambia',2005,NULL,NULL,50.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (270,'Gambia',2010,NULL,NULL,60.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (270,'Gambia',2015,NULL,NULL,70.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (275,'State of Palestine',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (275,'State of Palestine',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (275,'State of Palestine',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (276,'Germany',2005,NULL,99.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (276,'Germany',2010,NULL,99.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (276,'Germany',2015,NULL,99.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (288,'Ghana',2005,2.9,19,36.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (288,'Ghana',2010,4.7,22.8,40.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (288,'Ghana',2015,6.7,26.9,44);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (292,'Gibraltar',2005,NULL,99.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (292,'Gibraltar',2010,NULL,99.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (292,'Gibraltar',2015,NULL,99.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (300,'Greece',2005,NULL,98.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (300,'Greece',2010,NULL,98.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (300,'Greece',2015,NULL,98.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (304,'Greenland',2005,NULL,94.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (304,'Greenland',2010,NULL,96,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (304,'Greenland',2015,NULL,96.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (320,'Guatemala',2005,NULL,53.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (320,'Guatemala',2010,NULL,57.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (320,'Guatemala',2015,NULL,60.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (340,'Honduras',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (340,'Honduras',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (340,'Honduras',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (344,'China, Hong Kong SAR',2005,NULL,98.7,98.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (344,'China, Hong Kong SAR',2010,NULL,99.5,99.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (344,'China, Hong Kong SAR',2015,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (348,'Hungary',2005,NULL,57.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (348,'Hungary',2010,NULL,69.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (348,'Hungary',2015,NULL,81.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (352,'Iceland',2005,NULL,92.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (352,'Iceland',2010,NULL,95.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (352,'Iceland',2015,NULL,98.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (356,'India',2005,35.6,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (356,'India',2010,42.3,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (356,'India',2015,49.5,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (364,'Iran (Islamic Republic of)',2005,83,91.5,95.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (364,'Iran (Islamic Republic of)',2010,83,91.5,95);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (364,'Iran (Islamic Republic of)',2015,83.1,91.4,94.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (368,'Iraq',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (368,'Iraq',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (368,'Iraq',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (372,'Ireland',2005,NULL,94.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (372,'Ireland',2010,NULL,96.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (372,'Ireland',2015,NULL,98.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (376,'Israel',2005,99.4,99.4,99.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (376,'Israel',2010,99.4,99.4,99.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (376,'Israel',2015,99.4,99.4,99.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (380,'Italy',2005,NULL,89.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (380,'Italy',2010,NULL,92.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (380,'Italy',2015,NULL,93.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (384,'Côte d''Ivoire',2005,16.9,39.7,65.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (384,'Côte d''Ivoire',2010,20.1,43,65.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (384,'Côte d''Ivoire',2015,23.1,45.8,65);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (392,'Japan',2005,NULL,96.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (392,'Japan',2010,NULL,97,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (392,'Japan',2015,NULL,97.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (398,'Kazakhstan',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (398,'Kazakhstan',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (398,'Kazakhstan',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (400,'Jordan',2005,NULL,93.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (400,'Jordan',2010,NULL,93.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (400,'Jordan',2015,NULL,93.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (404,'Kenya',2005,NULL,NULL,59.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (404,'Kenya',2010,NULL,NULL,57.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (404,'Kenya',2015,NULL,NULL,54.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (410,'Republic of Korea',2005,NULL,96.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (410,'Republic of Korea',2010,NULL,97.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (410,'Republic of Korea',2015,NULL,98,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (414,'Kuwait',2005,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (414,'Kuwait',2010,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (414,'Kuwait',2015,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (417,'Kyrgyzstan',2005,30.5,48.7,82.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (417,'Kyrgyzstan',2010,40.7,57.2,87.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (417,'Kyrgyzstan',2015,51.6,66.3,92.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (419,'Latin America & the Caribbean',2005,NULL,62.3,77.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (419,'Latin America & the Caribbean',2010,NULL,63.6,76.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (419,'Latin America & the Caribbean',2015,NULL,65.4,76.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (422,'Lebanon',2005,NULL,45.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (422,'Lebanon',2010,NULL,46.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (422,'Lebanon',2015,NULL,47.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (428,'Latvia',2005,NULL,81.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (428,'Latvia',2010,NULL,81.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (428,'Latvia',2015,NULL,81.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (434,'Libya',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (434,'Libya',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (434,'Libya',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (438,'Liechtenstein',2005,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (438,'Liechtenstein',2010,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (438,'Liechtenstein',2015,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (440,'Lithuania',2005,NULL,75.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (440,'Lithuania',2010,NULL,83.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (440,'Lithuania',2015,NULL,91.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (442,'Luxembourg',2005,NULL,98.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (442,'Luxembourg',2010,NULL,98.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (442,'Luxembourg',2015,NULL,98.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (446,'China, Macao SAR',2005,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (446,'China, Macao SAR',2010,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (446,'China, Macao SAR',2015,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (458,'Malaysia',2005,NULL,93.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (458,'Malaysia',2010,NULL,92.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (458,'Malaysia',2015,NULL,92.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (470,'Malta',2005,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (470,'Malta',2010,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (470,'Malta',2015,NULL,99.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (474,'Martinique',2005,NULL,95.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (474,'Martinique',2010,NULL,99,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (474,'Martinique',2015,NULL,99.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (484,'Mexico',2005,NULL,40.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (484,'Mexico',2010,NULL,41.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (484,'Mexico',2015,NULL,42.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (492,'Monaco',2005,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (492,'Monaco',2010,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (492,'Monaco',2015,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (498,'Republic of Moldova',2005,NULL,48.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (498,'Republic of Moldova',2010,NULL,60.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (498,'Republic of Moldova',2015,NULL,70,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (499,'Montenegro',2010,NULL,89.2,94.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (499,'Montenegro',2015,NULL,89.7,93.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (504,'Morocco',2005,25.5,59.4,87);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (504,'Morocco',2010,32.1,64.3,87.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (504,'Morocco',2015,38.6,68.8,88.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (508,'Mozambique',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (508,'Mozambique',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (508,'Mozambique',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (512,'Oman',2005,NULL,74.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (512,'Oman',2010,NULL,82.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (512,'Oman',2015,NULL,88.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (524,'Nepal',2005,23.2,25,34.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (524,'Nepal',2010,24.2,25.9,34.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (524,'Nepal',2015,25.1,26.8,33.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (528,'Netherlands',2005,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (528,'Netherlands',2010,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (528,'Netherlands',2015,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (540,'New Caledonia',2005,NULL,88.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (540,'New Caledonia',2010,NULL,92.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (540,'New Caledonia',2015,NULL,97.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (554,'New Zealand',2005,NULL,76.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (554,'New Zealand',2010,NULL,88.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (554,'New Zealand',2015,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (558,'Nicaragua',2005,30.1,57,78.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (558,'Nicaragua',2010,29.8,57.8,78.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (558,'Nicaragua',2015,29.6,58.7,79.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (562,'Niger',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (562,'Niger',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (562,'Niger',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (566,'Nigeria',2005,NULL,18.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (566,'Nigeria',2010,NULL,19.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (566,'Nigeria',2015,NULL,19.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (570,'Niue',2005,NULL,98.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (570,'Niue',2010,NULL,97.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (570,'Niue',2015,NULL,97.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (578,'Norway',2005,NULL,95,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (578,'Norway',2010,NULL,95,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (578,'Norway',2015,NULL,95,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (580,'Northern Mariana Islands',2005,NULL,81.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (580,'Northern Mariana Islands',2010,NULL,82.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (580,'Northern Mariana Islands',2015,NULL,82.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (585,'Palau',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (585,'Palau',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (585,'Palau',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (586,'Pakistan',2005,31.9,38,49.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (586,'Pakistan',2010,32.2,36.9,45);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (586,'Pakistan',2015,32.4,35.6,40.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (591,'Panama',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (591,'Panama',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (591,'Panama',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (604,'Peru',2005,16,46.8,57.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (604,'Peru',2010,17.9,48.6,57.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (604,'Peru',2015,19.9,50.2,58.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (616,'Poland',2005,NULL,93.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (616,'Poland',2010,NULL,93.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (616,'Poland',2015,NULL,93.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (620,'Portugal',2005,NULL,94.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (620,'Portugal',2010,NULL,94.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (620,'Portugal',2015,NULL,95.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (630,'Puerto Rico',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (630,'Puerto Rico',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (630,'Puerto Rico',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (634,'Qatar',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (634,'Qatar',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (634,'Qatar',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (642,'Romania',2005,NULL,96,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (642,'Romania',2010,NULL,92.6,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (642,'Romania',2015,NULL,87.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (643,'Russian Federation',2005,NULL,75,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (643,'Russian Federation',2010,NULL,75.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (643,'Russian Federation',2015,NULL,75.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (646,'Rwanda',2005,NULL,NULL,29.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (646,'Rwanda',2010,NULL,NULL,32.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (646,'Rwanda',2015,NULL,NULL,36.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (666,'Saint Pierre and Miquelon',2010,NULL,83.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (666,'Saint Pierre and Miquelon',2015,NULL,83.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (674,'San Marino',2005,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (674,'San Marino',2010,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (674,'San Marino',2015,NULL,100,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (682,'Saudi Arabia',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (682,'Saudi Arabia',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (682,'Saudi Arabia',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (686,'Senegal',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (686,'Senegal',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (686,'Senegal',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (688,'Serbia',2005,NULL,77.8,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (688,'Serbia',2010,NULL,83.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (688,'Serbia',2015,NULL,88.1,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (702,'Singapore',2005,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (702,'Singapore',2010,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (702,'Singapore',2015,NULL,100,100);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (703,'Slovakia',2005,NULL,93.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (703,'Slovakia',2010,NULL,93.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (703,'Slovakia',2015,NULL,93.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (705,'Slovenia',2005,NULL,82.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (705,'Slovenia',2010,NULL,90.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (705,'Slovenia',2015,NULL,98,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (706,'Somalia',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (706,'Somalia',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (706,'Somalia',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (710,'South Africa',2005,NULL,NULL,90.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (710,'South Africa',2010,NULL,NULL,88.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (710,'South Africa',2015,NULL,NULL,85);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (724,'Spain',2005,NULL,98.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (724,'Spain',2010,NULL,98.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (724,'Spain',2015,NULL,98.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (748,'Swaziland',2005,NULL,NULL,75);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (748,'Swaziland',2010,NULL,NULL,82.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (748,'Swaziland',2015,NULL,NULL,88.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (752,'Sweden',2005,NULL,98,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (752,'Sweden',2010,NULL,98,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (752,'Sweden',2015,NULL,98,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (756,'Switzerland',2005,NULL,93.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (756,'Switzerland',2010,NULL,94.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (756,'Switzerland',2015,NULL,95.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (762,'Tajikistan',2005,NULL,40.9,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (762,'Tajikistan',2010,NULL,44.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (762,'Tajikistan',2015,NULL,47.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (784,'United Arab Emirates',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (784,'United Arab Emirates',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (784,'United Arab Emirates',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (788,'Tunisia',2005,NULL,62.5,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (788,'Tunisia',2010,NULL,89,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (788,'Tunisia',2015,NULL,92.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (792,'Turkey',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (792,'Turkey',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (792,'Turkey',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (795,'Turkmenistan',2005,61.4,73.6,87.3);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (795,'Turkmenistan',2010,73.5,79.8,86.4);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (795,'Turkmenistan',2015,86.8,86.1,85.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (798,'Tuvalu',2005,NULL,NULL,0);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (798,'Tuvalu',2010,NULL,NULL,0);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (798,'Tuvalu',2015,NULL,NULL,0);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (800,'Uganda',2005,1.9,4.6,22.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (800,'Uganda',2010,3,5.5,20.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (800,'Uganda',2015,4.3,6.4,17.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (804,'Ukraine',2005,NULL,70.4,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (804,'Ukraine',2010,NULL,84.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (804,'Ukraine',2015,NULL,92.2,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (807,'TFYR of Macedonia',2005,82.8,91.1,97.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (807,'TFYR of Macedonia',2010,89.1,91.2,92.8);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (807,'TFYR of Macedonia',2015,74.6,83.5,90.1);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (818,'Egypt',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (818,'Egypt',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (818,'Egypt',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (826,'United Kingdom',2005,NULL,95.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (826,'United Kingdom',2010,NULL,95.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (826,'United Kingdom',2015,NULL,95.7,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (830,'Channel Islands',2010,NULL,92,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (830,'Channel Islands',2015,NULL,92,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (833,'Isle of Man',2015,NULL,96.3,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (834,'United Rep. of Tanzania',2005,NULL,NULL,13.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (834,'United Rep. of Tanzania',2010,NULL,NULL,27.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (834,'United Rep. of Tanzania',2015,NULL,NULL,33.6);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (840,'United States of America',2005,NULL,99,99.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (840,'United States of America',2010,NULL,99,99.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (840,'United States of America',2015,NULL,99,99.7);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (858,'Uruguay',2005,NULL,NULL,93.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (858,'Uruguay',2010,NULL,NULL,94.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (858,'Uruguay',2015,NULL,NULL,94.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (860,'Uzbekistan',2005,31.6,51.6,86);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (860,'Uzbekistan',2010,31.1,51.2,86.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (860,'Uzbekistan',2012,31.1,51.2,86.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (860,'Uzbekistan',2015,NULL,NULL,86.5);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (862,'Venezuela (Boliv. Rep. of)',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (862,'Venezuela (Boliv. Rep. of)',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (862,'Venezuela (Boliv. Rep. of)',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (887,'Yemen',2005,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (887,'Yemen',2010,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (887,'Yemen',2015,NULL,NULL,NULL);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (894,'Zambia',2005,NULL,NULL,47.9);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (894,'Zambia',2010,NULL,NULL,47.2);
INSERT INTO drinking_water_availability(region,region_name,year,safe_drinking_water_rural,safe_drinking_water_total,safe_drinking_water_urban) VALUES (894,'Zambia',2015,NULL,NULL,46.5);
